"""add auth sessions infrastructure table

Revision ID: 29fac519f35f
Revises: 2d80cdb002f4
Create Date: 2026-08-22 22:25:29.587092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29fac519f35f'
down_revision: Union[str, None] = '2d80cdb002f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_auth_sessions_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_auth_sessions_user_id', 'auth_sessions', ['user_id'], unique=False)
    op.create_index('uq_auth_sessions_token_digest', 'auth_sessions', ['token_digest'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # MySQL cannot drop an index that a foreign key still requires
    # (error 1553), so the FK is removed before its supporting index.
    op.drop_constraint(
        "fk_auth_sessions_user_id_users", "auth_sessions", type_="foreignkey"
    )
    op.drop_index("uq_auth_sessions_token_digest", table_name="auth_sessions")
    op.drop_index("ix_auth_sessions_user_id", table_name="auth_sessions")
    op.drop_table("auth_sessions")
